### ISSUE TITLE
Adding contributors to readme.md

### ISSUE THREAD

**Issue by ComputerScientist-01** [ComputerScientist-01/Advanced-Programming-Practice#6]
So in the readme.md i wish to add this piece of code to display the contributors of this repository
```
<a href="https://github.com/ComputerScientist-01/Advanced-Programming-Practice/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=ComputerScientist-01/Advanced-Programming-Practice" />
</a>
```
and its not displaying correctly. Anyone willingness to solve would be appreciated

**Comment by ComputerScientist-01** [comment]
@sg23600

**Comment by sandip2224** [comment]
Why don't you try using **AllContributors** bot to resolve this issue?
Here the URL: [https://allcontributors.org/](https://allcontributors.org/)

**Comment by sandip2224** [comment]
When you mentioned `not displaying correctly`, what exactly do you mean?

**Comment by ComputerScientist-01** [comment]
So i added an image called contributors which is algined centrally 
after adding that piece of code it is not centered as it should be

**Comment by sandip2224** [comment]
You can close this issue now
